name: Build And Deploy Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          image: ${{ secrets.DOCKERHUB_USERNAME }}/cooking-recipes-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cooking-recipes-api:latest